INSERT INTO "public"."Answer" ("cardId", "text", "createdAt", "updatedAt") values
(1, 'village', now(), now()),
(2, 'to remove', now(), now()),
(2, 'remove', now(), now()),
(3, 'assistance', now(), now()),
(4, 'member of the crew', now(), now()),
(5, 'lack', now(), now()),
(6, 'receive', now(), now()),
(7, 'below', now(), now()),
(8, 'unusual', now(), now()),
(9, 'discomfort', now(), now()),
(11, 'measures', now(), now()),
(12, 'decay', now(), now()),
(13, 'the curfew', now(), now()),
(13, 'curfew', now(), now()),
(14, 'real estate agency', now(), now()),
(15, 'avocado', now(), now()),
(16, 'easy', now(), now()),
(17, 'łyżka', now(), now()),
(17, 'spoon', now(), now()),
(18, 'łyżka', now(), now()),
(18, 'spoon', now(), now()),
(19, 'premiere', now(), now()),
(19, 'premiera', now(), now()),
(20, 'release', now(), now()),
(21, 'essential', now(), now()),
(22, 'kupić', now(), now()),
(22, 'buy', now(), now()),
(23, 'teraz', now(), now()),
(23, 'now', now(), now()),
(24, 'płacić', now(), now()),
(24, 'pay', now(), now()),
(25, 'karta kredytowa', now(), now()),
(25, 'credit card', now(), now()),
(26, 'ratusz', now(), now()),
(26, 'town hall', now(), now()),
(26, 'city hall', now(), now()),
(27, 'wynajmować', now(), now()),
(28, 'umowa najmu', now(), now()),
(29, 'krewetka', now(), now()),
(29, 'shrimp', now(), now()),
(29, 'prawn', now(), now()),
(30, 'rak', now(), now()),
(31, 'a light', now(), now()),
(31, 'światło', now(), now()),
(32, 'fresh air', now(), now()),
(33, 'simple', now(), now()),
(34, 'move', now(), now()),
(35, 'place', now(), now()),
(36, 'courgette', now(), now()),
(36, 'cukinia', now(), now()),
(37, 'pan', now(), now()),
(37, 'patelnia', now(), now()),
(38, 'forever', now(), now()),
(39, 'receta', now(), now()),
(40, 'cocina', now(), now()),
(42, 'learn', now(), now()),
(42, 'nauczyć się', now(), now()),
(44, 'entender', now(), now()),
(44, 'comprender', now(), now()),
(45, 'do', now(), now()),
(45, 'robić', now(), now()),
(46, 'hacer', now(), now()),
(47, 'proposal', now(), now()),
(48, 'para ello', now(), now()),
(49, 'cut', now(), now()),
(50, 'fino', now(), now()),
(51, 'frío', now(), now()),
(52, 'carrot', now(), now()),
(52, 'marchewka', now(), now()),
(53, 'puedo', now(), now()),
(54, 'hoy', now(), now()),
(55, 'después', now(), now()),
(57, 'puedes repetir', now(), now()),
(57, 'puedes repetir?', now(), now()),
(58, 'nuestra', now(), now()),
(59, 'somos', now(), now()),
(60, 'deletrear', now(), now()),
(61, 'edad', now(), now()),
(62, 'palabra', now(), now()),
(64, 'decir', now(), now()),
(68, 'nueces', now(), now()),
(69, 'un quarto de gambas', now(), now()),
(70, 'voy a deletrear', now(), now()),
(71, 'el lunes', now(), now()),
(72, 'el martes', now(), now()),
(73, 'el miércoles', now(), now()),
(74, 'el jueves', now(), now()),
(10, 'will be', now(), now()),
(67, 'la nuez', now(), now()),
(56, 'dime', now(), now()),
(63, 'pedir', now(), now()),
(65, 'alguien', now(), now()),
(66, 'contestar', now(), now()),
(75, 'el viernes', now(), now()),
(77, 'el domingo', now(), now()),
(78, 'treinta', now(), now()),
(79, 'seis', now(), now()),
(80, 'siete', now(), now()),
(81, 'nueve', now(), now()),
(84, 'llegar', now(), now()),
(86, 'nuevo', now(), now()),
(89, 'creo', now(), now()),
(92, 'cuándo', now(), now()),
(92, 'cuando', now(), now()),
(94, 'cosa', now(), now()),
(101, 'delgado', now(), now()),
(101, 'fino', now(), now()),
(103, 'cerca', now(), now()),
(104, 'razón', now(), now()),
(107, 'mezcla', now(), now()),
(108, 'entre', now(), now()),
(109, 'dar', now(), now()),
(87, 'esperar', now(), now()),
(95, 'cumpleaños', now(), now()),
(88, 'espere', now(), now()),
(82, 'diez', now(), now()),
(97, 'paraguas', now(), now()),
(124, 'pobre', now(), now()),
(106, 'acostarse', now(), now()),
(144, 'me apetece', now(), now()),
(90, 'adivinar', now(), now()),
(116, 'yo doy', now(), now()),
(116, 'doy', now(), now()),
(143, 'chándal', now(), now()),
(129, 'apuntarse', now(), now()),
(135, 'pareja', now(), now()),
(126, 'invierno', now(), now()),
(111, 'casi', now(), now()),
(102, 'aburrido', now(), now()),
(127, 'hace frío', now(), now()),
(142, 'techo', now(), now()),
(113, 'reescribir', now(), now()),
(114, 'dar', now(), now()),
(85, 'venir', now(), now()),
(85, 'llegar', now(), now()),
(96, 'parar', now(), now()),
(105, 'dejar', now(), now()),
(105, 'salir', now(), now()),
(128, 'hace calor', now(), now()),
(83, 'a las nueve de la mañana', now(), now()),
(83, 'a las 9 de la mañana', now(), now()),
(138, 'para ello', now(), now()),
(125, 'empezar', now(), now()),
(112, 'pronombre', now(), now()),
(123, 'salgo', now(), now()),
(76, 'el sábado', now(), now()),
(118, 'conocer', now(), now()),
(118, 'saber', now(), now()),
(136, 'lejos', now(), now()),
(139, 'aunque', now(), now()),
(119, 'conozco', now(), now()),
(119, 'sé', now(), now()),
(140, 'suelo', now(), now()),
(140, 'piso', now(), now()),
(131, 'soñar', now(), now()),
(132, 'deuda', now(), now()),
(120, 'veo', now(), now()),
(99, 'bajar', now(), now()),
(130, 'entonces', now(), now()),
(133, 'perder peso', now(), now()),
(91, 'llevar', now(), now()),
(98, 'subir', now(), now()),
(145, 'tira', now(), now()),
(115, 'dar la mano', now(), now()),
(146, 'trozo', now(), now()),
(121, 'parecer', now(), now()),
(134, 'los demás', now(), now()),
(110, 'por lo menos', now(), now()),
(147, 'podré', now(), now()),
(93, 'cuánto?', now(), now()),
(150, 'desarrollo', now(), now()),
(151, 'barato', now(), now()),
(149, 'préstamo', now(), now()),
(148, 'sortear', now(), now()),
(43, 'aprender', now(), now()),
(100, 'alto', now(), now()),
(137, 'por eso', now(), now()),
(117, 'yo hago', now(), now()),
(117, 'hago', now(), now()),
(154, 'nunca', now(), now()),
(155, 'esta vez', now(), now()),
(153, 'ola', now(), now()),
(152, 'reemplazar', now(), now()),
(157, 'orgullo', now(), now()),
(156, 'amenaza', now(), now());

